version: '3.4'

services:
  efcoresqlserver:
    image: ${DOCKER_REGISTRY-}efcoresqlserver
    build:
      context: .
      dockerfile: EFCoreSqlServer/Dockerfile
    depends_on: 
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2017-latest
    hostname: 'sqlserver'
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: "Senha@123"
    volumes:
      - sqlserver_cursodocker:/var/opt/mssql3
    ports:
      - 11433:1433
    expose:
      - 1433

volumes:
  sqlserver_cursodocker: